"""
models/alert.py — Alert model.

Alerts are generated by the detection runner when a rule matches events.
Status transitions: open → investigating → closed (analyst triage workflow).
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class Alert(BaseModel):
    alert_id: str
    rule_id: str
    rule_name: str
    severity: str
    triggered_at: datetime
    event_count: int
    sample_event_ids: list[str] = Field(default_factory=list)
    status: Literal["open", "investigating", "closed"] = "open"
    notes: str = ""


class AlertPatch(BaseModel):
    """Partial update for triage — status and analyst notes."""

    status: Literal["open", "investigating", "closed"] | None = None
    notes: str | None = None
